version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"

  nlp:
    container_name: nlp
    hostname: nlp
    build:
      context: ./nlp
    command: ['python', 'main.py']
    # command: ['python', 'test.py']
    stdin_open: true
    tty: true
    volumes:
      - ./nlp:/usr/src/nlp
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - speech

  npm:
    container_name: npm
    hostname: npm
    build:
      context: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/usr/src/npm
    ports:
      - "3000:3000"

  backend:
    container_name: backend
    hostname: backend
    build:
      context: ./backend
    command: ["python", "main.py"]
    tty: true
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - "6677:6677"

  speech:
    container_name: speech
    hostname: speech
    build:
      context: ./speech
    command: ['python', 'main.py']
    # command: ['python', 'test.py']
    tty: true
    volumes:
      - ./speech:/usr/src/speech
    devices:
      - "/dev/snd:/dev/snd"
    depends_on:
      - redis